


CREATE TABLE `intuit`.`PRODUCT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DISPLAY_NAME` VARCHAR(100) NOT NULL,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
   PRIMARY KEY (`ID`) USING BTREE
);

CREATE TABLE `intuit`.`PROFILE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(255) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `SERVICE_SESSION_ID` VARCHAR(255) NOT NULL,
   PRIMARY KEY (`ID`) USING BTREE
);


CREATE TABLE `intuit`.`REVIEW` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `COMMENT` TEXT NOT NULL,
  `CREATED_DATE` DATE NOT NULL,
  `PROFILE_ID` INT(10) NOT NULL,
  `RATING` INT NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
   PRIMARY KEY (`ID`) USING BTREE,
   FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
   FOREIGN KEY (PROFILE_ID) REFERENCES PROFILE(ID)
);

INSERT INTO PRODUCT VALUES (100, "turbotax", "turbo tax for tax calculation purpose");
INSERT INTO PRODUCT VALUES (200, "small business product", "Software for small business purposes");
INSERT INTO PRODUCT VALUES (300, "Product1", "This is product 1");
INSERT INTO PRODUCT VALUES (400, "Product 2", "This is product 2");

INSERT INTO PROFILE VALUES (10000, "karthik", "password", "abc-def-ghi");
INSERT INTO PROFILE VALUES (10001, "mark", "password", "abc-123-def");
INSERT INTO PROFILE VALUES (10002, "samuel", "password", "123-456-678");
INSERT INTO PROFILE VALUES (10003, "mark", "password", "jui-uij-try");


